### ISSUE TITLE
Not receiving all :key-release events

### ISSUE THREAD

**Issue by noctuid** [sharplispers/clx#64]
These are the basics of a program I'm testing:
```
(defun grab-keys ()
  (let* ((screen (display-default-screen *display*))
         (root-window (screen-root screen)))
    (dolist (key *grab-keys*)
      (grab-key root-window (key->keycode key)
                :modifiers nil))))

(defun main ()
  (let ((*display* (open-display "")))
    (grab-keys)
    (loop (event-case (*display*)
            (:key-press
             (code)
             (format t "press: ~a~%" (keycode->key code))
             t)
            (:key-release
             (code)
             (format t "release: ~a~%" (keycode->key code))
             t)))))
```

I'm grabbing all of the letter keys. This works fine if I type keys individually. Once I start typing normally (rolling between keys), not all key release events are printed. For example, if I roll from `j` to `k`, `k`'s release is not reported:

```
press: j
press: k
release: j
```

When there is overlap, I only get the first key's release. I'm not sure if I'm doing something incorrectly or if this is a problem somewhere else. Any ideas?

**Comment by dkochmanski** [comment]
It looks like we have some variable which holds pressed key and doesn't get overwritten. We should fix it by consing key on some sort of list for each one.

**Comment by uint** [comment]
It appears the problem is in the way keys are grabbed with `(grab-key)`.

If I make it so that only keys `1` and `2` are grabbed (and not the `m` key!), and then sequentially press `m`, press `1`, release `m`, release `1`, I get:
```
press: 1
release: m
release: 1
```

On the other hand, replacing the `(grab-key)` loop with a `(grab-keyboard)` call makes everything work properly.

**Comment by uint** [comment]
Considering all `(grab-key)` does is send a `xgrabkey` request to the X server, I feel like this might be an upstream problem, though I didn't manage to find an existing bug report.

**Comment by dkochmanski** [comment]
please provide full program including how `*grab-keys*` how it is populated, key->keysym programs etc, so I can run it in my session. Thanks.

**Comment by dkochmanski** [comment]
there had to be something wrong with your program, because all works as desired (even if I have two keys pressed at once).

I've curbed clock demo with this:

```
(defun clock ()
  (xlib:map-window *win*)
  (loop
     (xlib:grab-key *win* :any :modifiers nil)
     (xlib:event-case (*display* :discard-p t)
       (:key-press
        (code)
        (format t "press: ~a~%" code)
        t)
       (:key-release
        (code)
        (format t "release: ~a~%" code)
        t))))
```

and all press / release events are correctly reported.

**Comment by noctuid** [comment]
I get the same behavior with your example. The second key release is never reported regardless of the two keys used. I'm using the quicklisp version but can try using the latest commit.

**Comment by dkochmanski** [comment]
Hm, clx didn't have improvements in these parts of the code. Also, we simply follow the protocol in a dumb way (that is - we simply receive events). That may be a clue, that the problem lies on Xserver side and was fixed in my version (1.19.5) and yours doesn't have this fix (basically what @uint suggested, that it is the upstream problem).

**Comment by noctuid** [comment]
I still have this issue on 1.19.5 and 1.19.6. Do you have any other ideas about why this would work for you but not me?

**Comment by dkochmanski** [comment]
I use XWayland on my host, so maybe it does better job than xf86-input-evdev (or whichever driver you use)? – In that case trying to switch to another input device may solve your problem (driver installed on my system is `xserver-xorg-input-libinput`).
